---
- name: MANAGER - Start the Registry service
  become: true
  when: "'managers' in group_names and registry_running.stdout == ''"
  docker_compose:
    project_name: registry
    definition:
      version: '2'
    services:
      registry:
        image: registry:latest
        volumes:
          - "{{ project_root_directory }}/.docker_volumes/registry"
        ports:
          - "{{ docker_registry_port }}:5000"
