---
- name: ALL - Install pip
  become: true
  apt:
    name: python3-pip
    state: latest
    force_apt_get: yes
  when: "'managers' in group_names"

- name: ALL - Install pip-docker
  become: true
  pip:
    name: docker
    state: present
- name: Install latest docker python bindings
  pip:
    name: "{{ packages }}"
    executable: pip3
    state: latest
  vars:
    packages:
      - docker
      - jsondiff
      - pyyaml
      - docker-compose
  become: true
