---
- name: Reconfigure GitLab
  become: true
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: MANAGER - Create SSL configuration folder
  become: true
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: "'managers' in group_names and gitlab_create_self_signed_cert"

- name: MANAGER - Create self-signed certificate
  become: true
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}" -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: "'managers' in group_names and gitlab_create_self_signed_cert"

- name: MANAGER - Copy GitLab configuration file
  become: true
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
  when: "'managers' in group_names"
# 
# - name: MANAGER - Create users
#   become: true
#   script: "{{ playbook_dir }}/gitlab.py {{ hostvars['manager']['ansible_default_ipv4']['address'] }}"
